### ISSUE TITLE
add copyright statement and license 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#1]
I see that the Plugin-MWS license is public domain, is is OK to have a different license for this plugin? I would prefer GPL. Up till now I had the LPPL which would also be OK.

**Comment by dginev** [comment]
You can specify any license for a plugin, they are independent entities from LaTeXML and are self-contained wrt licensing. Since I think I helped with the MWS plugin while I was at NIST, I kept it on the safe side and released anything I did at the time in the public domain.

You can even have a rather restrictive license in place, see for instance the SENNA plugin I had made a few years back:
* Copyright statement: https://metacpan.org/pod/Lingua::EN::SENNA#COPYRIGHT
* SENNA license file: https://metacpan.org/source/DGINEV/Lingua-EN-SENNA-0.04/LICENSE

which forbids use for non-research purposes explicitly! The SENNA author was happy to let me redistribute the SENNA sources in the plugin (and make it self-contained) once I had that bit of licensing information in there.

As long as the LICENSE files is epxlicit, anything goes.

**Comment by kohlhase** [comment]
thanks for the clarification, re-assigning to myself. I will use the lppl, that was what we used before.

**Comment by kohlhase** [comment]
I have given a license. What about the copyright statement?

**Comment by dginev** [comment]
Unsure if a "copyright statement" is explicitly necessary. It's a usual addendum in the perldoc documentation, so we could always add a bit of perldoc to the .ltxml bindings - but that's optional.

**Comment by kohlhase** [comment]
OK, then I guess the copyright statement in the headers is good enough.
