### ISSUE TITLE
\usemodule should not be counted in import cycle

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#71]
The main difference between ```\importmodule``` and ```\usemodule``` is that the symbols that come in via ```\usemodule``` are not re-exported. Therefore ```\usemodule``` plays no role in "import cycles". 

BUT in the implementation in ```modules.sty.ltxml```, ```\usemodule``` and ```\importmodule``` are essentially the same (crucially they both use ```&importmoduleI```). I think that we need to make a variant ```&usemoduleI``` of ```&importmoduleI``` that does not 
1. check for cycles, and more crucially
2. does not register the current "uses" relation into the cycle detection. 
The only thing we really want from ```&usemoduleI``` is that it loads the SMS file. 

BTW, this also is a problem for ```\usemhmodule``` as well. You can verify this error by converting ```MathHub/MiKoMH/GenCS/source/www/en/dhtml-applications.tex```, which gives the error. 
```
Fatal::module "html" leads to import cycle! 
Trace: html -> markup -> filetypes -> http -> application-layer -> webbrowser -> www-concepts -> internetweb -> systems -> operatingsystems -> CSS -> html: 
	/Users/kohlhase/localmh/MathHub/MiKoMH/GenCS/source/www/en/css.sms#textrange(from=1;1,to=2;97)
	In Core::Definition::Constructor[\import... from modules.sty.ltxml line 144
```
This error message is a bit weird anyway: ```html``` imports ```markup``` which imports ```filetypes``` which imports nothing (actually uses some things which are not reported here. So ```markup -> filetypes ->``` should not be in the cycle at all. 
But ```html``` also imports ```http```, which imports ```application-layer```  ....
And I have no idea where the ```webbrowser``` dependency comes from none of the previous ones seems to ```use``` or ```import``` it. So maybe this error is not about ```\importmodule``` or ```\usemodule``` after all, or the error message is just very confused. 

Fixing this has quite some priority for me, since it causes a lot of errors in MathHub (and I am starting to see the usefulness of ```\usemhmodule``` and use it more and more. 
cc: @dginev

**Comment by angerhang** [comment]
Actually `webbrowser` dependency comes from `browser-rendering-pipeline` which is used at `script` and `script` is imported from `dhtml-applications` 

But I don't understand why `markup -> filetypes ->` shouldn't be in the cycle as we have 
```tex
\begin{module}[id=markup]%
\importmodule[load=/mounted/lmh/MathHub/MiKoMH/TDM/source/digdocs/en/filetypes,ext=sms]{filetypes}%
\end{module}%
```
in `markup.sms ` and 
```tex
\begin{module}[id=html]%
\importmodule[load=/mounted/lmh/MathHub/MiKoMH/TDM/source/digdocs/en/markup,ext=sms]{markup}%
\importmodule[load=/mounted/lmh/MathHub/MiKoMH/GenCS/source/www/en/http,ext=sms]{http}%
\symdef{html}{\operatorname{HTML}}%
\end{module}%
```
in `html.sms`

**Comment by kohlhase** [comment]
> Actually webbrowser dependency comes from browser-rendering-pipeline which is used at script and script is imported from dhtml-applications

you are right about this.

**Comment by kohlhase** [comment]
What confuses me about the error message that what looks like a cycle is actually a call tree, which is linearized to a cyclic sequence and -> is not the "imports" relation. What I would have expected to see is a "minimal cycle", which this is not. 
> But I don't understand why markup -> filetypes -> shouldn't be in the cycle as we have
I just meant to say that markup -> filetypes cannot be part of a minimal cycle, since filetypes does not import anything.
I think that a better error message with a minimal cycle would help debugging greatly.

**Comment by kohlhase** [comment]
I have just written down the whole imports graph and verified that there is no cycle. It seems to me that the cycle recording mechanism is wrong; in particular, this may be independent of the ```\usemodule``` part. It seems that there is no ```\usemhmodule``` in the ```www``` directory.

**Comment by angerhang** [comment]
I also I agree with what you said that there is no import cycle. It is the cycle recording mechanism that mistakenly thinks the two times html import makes up a cycle:

<img width="686" alt="screen shot 2016-03-27 at 7 54 02 pm" src="https://cloud.githubusercontent.com/assets/7655454/14066847/afaccc14-f455-11e5-9fe2-4884be45dcc2.png">

**Comment by angerhang** [comment]
The actual cause of this is the ancestors array of `css` contains all the right subtree of `dhtml` such that 
```perl
 if (defined $ancestors{$module}) {
    my $trace = join(" -> ",(@{$ancestors{__trace}},$module));
    Fatal(":module \"$module\" leads to import cycle! \nTrace: $trace");
  }
```
throws an error

**Comment by angerhang** [comment]
An easy fix can be deleting the cycle detection which is already done via 48f7a2c74f242d94e3ae4c339d6b9692b7142b0c. This patch only imports the modules that have not be imported. 

In this way we will never have a cyclic importing but won't be able to detect any cycle either. It would be fine if LaTeX would complain about cyclic importing. Need to confirm with @kohlhase .

The old cycle detection approach doesn't work in the case of having two `html`s even if these two do not necessarily make up a cycle. If we really want to have a proper cycle detection, we probably should use a tree structure.

**Comment by dginev** [comment]
I'm worried about ```%ancestors``` recording the wrong information for some bizarre reason. Rather than collecting a trace in ancestors, I would print the ```$module``` variable, as the call descends, together with a ```Dumper(%ancestors)```, to make sure the recorded hash is meaningful.

If the recursive descent is correct, there is no reason for a flat hash to be insufficient here, but it is crucial that the information in the ancestors hash is correct as the descent happens, which depends on it being copied by value and not by reference.

**Comment by dginev** [comment]
Actually, this is probably the reason your trace is wrong - you are storing an array reference in ```$ancestors{___trace}```, so you end up effectively using a global trace variable for the descent into ```dhtml```, as passing an array reference by value just copies a pointer, and not the content.

The idea behind ```%ancestors``` is that it is a flat hash, copied by value, so that at any stage of the descent it only contains the ancestors for that stage, and no other. And that should work correctly if the descent happens normally. There is often a trickier bug, related to incorrect module loading, rather than a cycle detection bug.

**Comment by angerhang** [comment]
Deyan you are right about this. `%ancestors` is recoding the wrong information for some other reason. 

It was because the recursive descent not being correct, I thought of an easy fix instead.

In fact the recursive descent is correct when it loads everything from the right subtree in the example above, the tricky bit is that when the search finishes the right subtree and goes to `CSS` as of a depth first search, `CSS`'s ancestors will contain every node from the right subtree namely `script, broser-rendering, html, ..., interntweb`

**Comment by kohlhase** [comment]
I am quite surprised that this only appears now. Was there any change in the code? I would have expected that if there are cycle detection problems, they would have surfaced long long ago.

**Comment by angerhang** [comment]
Aha this rings a bell for me. 

I think I did change this part of code some time ago. This is to blame. Didn't know this change would introduce such a regression error plus the provide theory is not using the `current_module` value anymore. We should probably change it back and I will add a test case about this as well.

https://github.com/KWARC/LaTeXML-Plugin-sTeX/commit/5277c8f0bdbb98f9007ea547964cce8f476bbb7c#diff-1b344a1dbd42a549b40461d8ed41aa23R94
